### ISSUE TITLE
Cardboard Box Crashes Client when used on a spawner

### ISSUE THREAD

**Issue by Lopezak** [IamRyan30/Decursio-Team#3]
### Modpack Version

Beta 21.3

### Launcher Used

Curseforge

### Did this issue occur on Multiplayer, Singleplayer, or both?

Multiplayer Only

### Do you, or did you had Optifine installed when the issue took place?

Yes

### Tried reproducing without Optifine?

Yes

### Describe your issue

Attempted to use Cardboard box from Mekanism on spawner in the world. Upon using the cardboard box from Mekanism on the spawner, the client of the user experiences a crash. The server, or other clients on the server, do not show any signs of reaction. The cardboard box does not apply to the spawner. Player is able to rejoin successfully as well after crash. Was tried with and without optifine, results were the same.

### Log File related to your issue

https://drive.google.com/file/d/1u1dY0tUXm2o8k3_pCgs0I3PA-HhCQVL9/view?usp=sharing

### Crash Report

https://crashy.net/IJmpswpZP0OwZEixrtad

### Other mods

None

### Searched for known issues?

Checked know-issues, Checked faq, Searched open issues, Searched closed issues

**Comment by IamRyan30** [comment]
Both of these link are for the crash file. A log from the server and the client might be useful. I'll try to reproduce this when I get some free time. Meanwhile, if you can, try to update to the 24th version of the pack. Things might work there.

I know you said you reverted because the recipes for the Crucible from Immersive Industry, were gone. That was fixed, so I'd say you can update. That's ofc, if you're that person on my discord server. If you're not, ignore this part.

**Comment by Lopezak** [comment]
Yup, same guy. I just figured I'd throw this up there. Didn't see that update 24 released. I'll give those things a shot. Should be simple to reproduce, although I only experienced it on MP as stated. If it's still producing the issue in 24, I'll put together the logs for you. Didn't realize they were the same file my bad on that.

**Comment by Lopezak** [comment]
Beta 24 would seem to have fixed this problem somehow. Closing
